CREATE DATABASE IF NOT EXISTS INVENTARIO_DEMO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE INVENTARIO_DEMO;

CREATE TABLE IF NOT EXISTS USUARIOS(
ID INT PRIMARY KEY AUTO_INCREMENT,
PASS BINARY(32),
EMAIL VARCHAR(30),
USERNAME VARCHAR(30)
);

CREATE TABLE IF NOT EXISTS PASSWORD_RESETS(
ID INT PRIMARY KEY AUTO_INCREMENT,
EMAIL VARCHAR(30),
TOKEN VARCHAR(32),
EXPIRACION DATETIME,
USADO TINYINT(1) DEFAULT 0
);

CREATE TABLE IF NOT EXISTS PRODUCTOS(
ID INT PRIMARY KEY AUTO_INCREMENT,
PRODUCTO VARCHAR(30),
STOCK INT,
ULTIMA_ACTUALIZACION DATETIME DEFAULT CURRENT_TIMESTAMP,
USERNAME INT,
FOREIGN KEY (USERNAME) REFERENCES USUARIOS(ID)
);